### ISSUE TITLE
Problem to show file content when using  more than one file and custom layout

### ISSUE THREAD

**Issue by tinchox5** [google/playground-elements#384]
Hi there!
I'm using a custom layout based on this example https://github.com/google/playground-elements#custom-layouts.

Since I need to use more than one file I added `playground-tab-bar` component, which is rendered ok. The problem arise when I want to select another file: the new content is not rendered/updated into `playground-file-editor`. 

Here is my code.
```html
<playground-project id="project1"  >   
<script type="sample/html" filename="index.html">
<!doctype html>
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="ie=edge" />
<link rel="stylesheet" href="styles.css">
</head>
<body>
<section  class="o-container one ">
<ul  class="o-orbit">
    <li class="o-orbiter"></li>
    <li class="o-orbiter"></li>
    <li class="o-orbiter"></li>
    <li class="o-orbiter"></li>
    <li class="o-orbiter"></li>
</ul>
</section>
</body>
</script>
<script type="sample/css" filename="styles.css">
.o-orbiter {
border: 7px solid mediumaquamarine;
}
.o-container {
border: 0.2px solid gray;
}
.one {
border: 2px solid;
padding: 20px; 
}
</script>
</playground-project>
<div class="example">
    <playground-tab-bar project="project1"></playground-tab-bar>
    <playground-file-editor  project="project1"></playground-file-editor>
    <playground-preview project="project1"> </playground-preview>
</div>  
```

And  css style: 

```css
.example {
  width: 100%;
  border: 1px solid #ccc;
  overflow: hidden;
  border-radius: 10px;
}
.example > playground-file-editor {
  height: 300px;
}
.example > playground-preview {
  height: max-content;
  border-top: 1px solid #ccc;
  --playground-preview-toolbar-background: #eaeaea;
}
```
